# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEntity.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addEntityDialog(object):
    def setupUi(self, addEntityDialog):
        addEntityDialog.setObjectName("addEntityDialog")
        addEntityDialog.resize(495, 688)
        addEntityDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox = QtWidgets.QDialogButtonBox(addEntityDialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 610, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(addEntityDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 441, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_entities = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_entities.setObjectName("comboBox_entities")
        self.comboBox_entities.addItem("")
        self.gridLayout.addWidget(self.comboBox_entities, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox_isAlive = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_isAlive.setObjectName("checkBox_isAlive")
        self.gridLayout.addWidget(self.checkBox_isAlive, 10, 0, 1, 2)
        self.lineEdit_locationX = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_locationX.setObjectName("lineEdit_locationX")
        self.gridLayout.addWidget(self.lineEdit_locationX, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit_Orientation = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Orientation.setObjectName("lineEdit_Orientation")
        self.gridLayout.addWidget(self.lineEdit_Orientation, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.comboBox_action = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_action.setEditable(True)
        self.comboBox_action.setObjectName("comboBox_action")
        self.comboBox_action.addItem("")
        self.comboBox_action.addItem("")
        self.comboBox_action.addItem("")
        self.comboBox_action.addItem("")
        self.comboBox_action.addItem("")
        self.comboBox_action.addItem("")
        self.gridLayout.addWidget(self.comboBox_action, 11, 1, 1, 1)
        self.lineEdit_locationY = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_locationY.setObjectName("lineEdit_locationY")
        self.gridLayout.addWidget(self.lineEdit_locationY, 5, 1, 1, 1)
        self.lineEdit_appearTime = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_appearTime.setObjectName("lineEdit_appearTime")
        self.gridLayout.addWidget(self.lineEdit_appearTime, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 1, 1, 1, 1)

        self.retranslateUi(addEntityDialog)
        self.buttonBox.accepted.connect(addEntityDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(addEntityDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addEntityDialog)

    def retranslateUi(self, addEntityDialog):
        _translate = QtCore.QCoreApplication.translate
        addEntityDialog.setWindowTitle(_translate("addEntityDialog", "Dialog"))
        self.comboBox_entities.setItemText(0, _translate("addEntityDialog", "Choose Entity to duplicate"))
        self.label.setText(_translate("addEntityDialog", "Entity"))
        self.checkBox_isAlive.setText(_translate("addEntityDialog", "is alive"))
        self.label_5.setText(_translate("addEntityDialog", "New Entity Name"))
        self.label_11.setText(_translate("addEntityDialog", "action"))
        self.label_4.setText(_translate("addEntityDialog", "Heading"))
        self.label_3.setText(_translate("addEntityDialog", "Location y"))
        self.label_9.setText(_translate("addEntityDialog", "appearence time"))
        self.comboBox_action.setItemText(0, _translate("addEntityDialog", "shut-arrived-enemy-leader"))
        self.comboBox_action.setItemText(1, _translate("addEntityDialog", "shut-arrived-enemy-second"))
        self.comboBox_action.setItemText(2, _translate("addEntityDialog", "turn-pix-right"))
        self.comboBox_action.setItemText(3, _translate("addEntityDialog", "turn-pix-left"))
        self.comboBox_action.setItemText(4, _translate("addEntityDialog", "keep-same"))
        self.comboBox_action.setItemText(5, _translate("addEntityDialog", "random"))
        self.label_2.setText(_translate("addEntityDialog", "Location x"))
