# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 822)
        self.layoutWidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 611, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ui = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(24)
        self.label_ui.setFont(font)
        self.label_ui.setText("")
        self.label_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ui.setObjectName("label_ui")
        self.verticalLayout.addWidget(self.label_ui)
        self.pushButton_openTQL = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_openTQL.setFont(font)
        self.pushButton_openTQL.setObjectName("pushButton_openTQL")
        self.verticalLayout.addWidget(self.pushButton_openTQL)
        self.pushButton_openEntities = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        self.pushButton_openEntities.setFont(font)
        self.pushButton_openEntities.setObjectName("pushButton_openEntities")
        self.verticalLayout.addWidget(self.pushButton_openEntities)
        self.pushButton_openRules = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_openRules.setFont(font)
        self.pushButton_openRules.setObjectName("pushButton_openRules")
        self.verticalLayout.addWidget(self.pushButton_openRules)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(155, 2, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(54, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_loadedFile = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_loadedFile.setGeometry(QtCore.QRect(170, 153, 421, 22))
        self.lineEdit_loadedFile.setObjectName("lineEdit_loadedFile")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setGeometry(QtCore.QRect(210, 100, 195, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_load = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.pushButton_save = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.pushButton_openTQL.setText(_translate("MainWindow", "TQL"))
        self.pushButton_openEntities.setText(_translate("MainWindow", "Entities"))
        self.pushButton_openRules.setText(_translate("MainWindow", "Rules"))
        self.label.setText(_translate("MainWindow", "Hagnash UI"))
        self.label_2.setText(_translate("MainWindow", "Loaded File"))
        self.pushButton_load.setText(_translate("MainWindow", "Load Data"))
        self.pushButton_save.setText(_translate("MainWindow", "Save Data"))
