# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimDialog(object):
    def setupUi(self, SimDialog):
        SimDialog.setObjectName("SimDialog")
        SimDialog.resize(701, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimDialog.sizePolicy().hasHeightForWidth())
        SimDialog.setSizePolicy(sizePolicy)
        self.openGLWidget = OGLWidget(SimDialog)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 0, 681, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget.sizePolicy().hasHeightForWidth())
        self.openGLWidget.setSizePolicy(sizePolicy)
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton_save = QtWidgets.QPushButton(SimDialog)
        self.pushButton_save.setGeometry(QtCore.QRect(300, 700, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.label = QtWidgets.QLabel(SimDialog)
        self.label.setGeometry(QtCore.QRect(12, 705, 251, 16))
        self.label.setObjectName("label")
        self.pushButton_load = QtWidgets.QPushButton(SimDialog)
        self.pushButton_load.setGeometry(QtCore.QRect(420, 700, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_clear = QtWidgets.QPushButton(SimDialog)
        self.pushButton_clear.setGeometry(QtCore.QRect(540, 700, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(SimDialog)
        QtCore.QMetaObject.connectSlotsByName(SimDialog)

    def retranslateUi(self, SimDialog):
        _translate = QtCore.QCoreApplication.translate
        SimDialog.setWindowTitle(_translate("SimDialog", "Add Entities"))
        self.pushButton_save.setText(_translate("SimDialog", "Save"))
        self.label.setText(_translate("SimDialog", "Press anywhere on the map to add entity"))
        self.pushButton_load.setText(_translate("SimDialog", "Load"))
        self.pushButton_clear.setText(_translate("SimDialog", "Clear"))
from myMain import OGLWidget
